Added Translations for !tracked
KartulUdus/PoracleJS pull request #203
Opened 2020-11-26 11:03 UTC by bbdoc

Added translations to !tracked as most text was harcoded and not going through the translator. Everything is now going through the translator.

Added translation for monsters shown in !tracked as you could add monsters to tracking in your local languages but they were still being shown in English when using !tracked.

Added French translations to fr.json for all existing translated items in !tracked + all new items added to translator.

Tested on my instance, running fine.

![Poracle](https://user-images.githubusercontent.com/23477802/100343152-495d5d00-2fdf-11eb-9134-112dd3e44ee4.png)

2020-11-27 20:29 UTC, jfberry commented on src/lib/discord/commando/commands/tracked.js
> +			message = message.concat('\n\n', client.translator.translate('You\'re  tracking the following monsters:'),'\n')
Worth fixing the double space here

2020-11-27 20:31 UTC, jfberry requested changes
Superb piece of work, some minor typos (some were already in the source and some you have introduced) would make this a no-brainer

2020-11-27 20:31 UTC, jfberry commented on src/lib/discord/commando/commands/tracked.js
> +		} else message = message.concat('\n\n', client.translator.translate('You\'re not tracking any monster'))
You have lost the plural 'tracking any monsters'

2020-11-27 20:31 UTC, jfberry commented on src/lib/discord/commando/commands/tracked.js
> +			message = message.concat('\n\n', client.translator.translate('You\'re  tracking the following raids:'),'\n')
extra space

2020-11-27 20:31 UTC, jfberry commented on src/lib/discord/commando/commands/tracked.js
> +		} else message = message.concat('\n\n', client.translator.translate('You\'re not tracking any raid'))
missing plural

2020-11-27 20:31 UTC, jfberry commented on src/lib/discord/commando/commands/tracked.js
> +			message = message.concat('\n\n', client.translator.translate('You\'re  tracking the following quests:'),'\n')
extra space

2020-11-27 20:31 UTC, jfberry commented on src/lib/discord/commando/commands/tracked.js
> +		} else message = message.concat('\n\n', client.translator.translate('You\'re not tracking any quest'))
missing plural

2020-11-27 20:31 UTC, jfberry commented on src/lib/discord/commando/commands/tracked.js
> +			message = message.concat('\n\n', client.translator.translate('You\'re  tracking the following invasions:'),'\n')
extra space

2020-11-27 20:31 UTC, jfberry commented on src/lib/discord/commando/commands/tracked.js
> +		} else message = message.concat('\n\n', client.translator.translate('You\'re not tracking any invasion'))
missing plural

2020-11-27 20:46 UTC, bbdoc commented
Thanks, that's corrected. I indeed thought that "not any" was taking a singular as there is logically 0, as would be the case in french ;-) but you are right, I learned something new today ;-) 

`not any is plural with plural count nouns and singular with non-count nouns`

2020-11-27 21:10 UTC, bbdoc commented on src/lib/discord/commando/commands/tracked.js
> +			message = message.concat('\n\n', client.translator.translate('You\'re  tracking the following quests:'),'\n')
Done

2020-11-27 21:11 UTC, jfberry commented
All changes look good -- ready for merge!

2020-12-18 14:20 UTC, jfberry commented
Merged these changes by hand, thanks bbdoc!

2020-12-18 14:20 UTC, closed without merging