Rework of Weather Management
KartulUdus/PoracleJS pull request #262
Opened 2021-01-16 15:50 UTC by Petap0w

__Complete rethink of Weather management including:__
A - Weather change alerts from Weather Webhooks (RDM included)
B - Weather change alerts from boosted Pokémons in the s2cell
C - Weather Forecast based on AccuWeather data to show on Pokémon alerts if the weather changes are likely to change boost status and stats
All those features are independent and can be set in config with the new `weather` section:
```
    "weather": {
        "weatherChangeAlert": false,                  // To enable or disable the weather change alerts
        "enableWeatherForecast": false,            // To enable or disable weather forecast
        "apiKeyAccuWeather": ["key1", "key2", "key3"],       // AccuWeather API keys
        "apiKeyDayQuota": 50,                           // Maximum API calls allowed per day
        "localFirstFetchHOD": 3,                        // First hour of the day for the first API call
        "forecastRefreshInterval": 8                  // API call interval
    },
```

__Requirements:__
- Webhook of the `weather` type for feature A (`config > general > disableWeather` set to `false`)
- Just the normal `pokemon` type webhooks for feature B (`config > general > disablePokemon` set to `false`)
- AccuWeather API app key for feature C
Register on AccuWeather website and create an APP which will grant you an API key. You can make 50 calls per day with one key. Depending on the interval you'll set to fetch forecast data, this can cover around 15 level 10 s2cells per day (with getting weather every 8 hours)

__Features A and B:__
When weather in a s2cell changes compared to last hour, all the users (or channels) who were caring about a Pokémon in that cell will receive a Weather change alert:
![Capture d’écran 2021-01-16 à 16 32 26](https://user-images.githubusercontent.com/47784174/104815993-7298ad80-5818-11eb-9421-c8e3cfc42d43.png)
This example is using the new `pokemon-weather` tileserver template available in the example folder (copy to your tileserver). The template expects `{latitude: double, longitude: double, condition: int, coords: [[lat1,lon1],[lat2,lon2],[lat3,lon3],[lat4,lon4]]}` and is fully integrated with the `tileservercache` staticProvider option in Poracle.

__Feature C:__
When a Pokémon webhook is analyzed, and if it despawns after the next hour mark, if the weather for next hour is different and will not boost anymore / will newly boost the Pokémon, then some new DTS are available on the alert:
```
weatherChange -> an already formed sentence for this weather change
weatherCurrent -> current weather ID
weatherCurrentName -> current weather
weatherCurrentEmoji -> current weather emoji
weatherNext -> weather ID forecast for next hour
weatherNextName -> weather name for next hour
weatherNextEmoji -> weather emoji for next hour
weatherChangeTime -> change time (format HH:00)
```
Giving:
![Capture d’écran 2021-01-16 à 16 42 14](https://user-images.githubusercontent.com/47784174/104816214-e7b8b280-5819-11eb-902e-db051bbafd67.png)

2021-01-16 23:14 UTC, ccev commented
A possible feature you could add would be the editing of a message to change `Weather might change` to `Weather & Stats changed`/`Weather did not change`.
No idea about Telegram, but Discord Bots and [recently Webhooks](https://discord.com/developers/docs/resources/webhook#modify-webhook) would allow this.

2021-01-18 10:49 UTC, muckelba commented
> No idea about Telegram, but Discord Bots and [recently Webhooks](https://discord.com/developers/docs/resources/webhook#modify-webhook) would allow this.

Telegram is able to do that. Should be pretty easy to implement because Poracle already have those message IDs to clean them later. Docs: https://core.telegram.org/bots/api#editmessagetext

2021-01-20 19:35 UTC, acocalypso commented
Looks good for me, no issues found so far.

2021-01-20 21:11 UTC, kamieniarz commented
I've been testing it for few days also and it works flawless

2021-01-23 13:47 UTC, t00fan commented
Been testing this for the last several days, and it's been working great!

2021-01-23 15:22 UTC, jfberry commented on src/app.js
> +					if (['telegram:user', 'telegram:channel'].includes(job.type)) fastify.telegramQueue.push(job)
think telegram:group missing here

2021-01-25 01:25 UTC, kbtbc commented
Been running this for a couple of days (only change notifications, no forecasting)...   seems to be working well.   Some users like them, some are asking for a way to disable them.  I don't know how complicated it would be, but a user-level toggle to choose to get weather notifications or not has been requested.

2021-01-25 19:18 UTC, kbtbc requested changes

2021-01-25 19:18 UTC, kbtbc commented on config/defaults/dts.json
> +        "description": "The weather for some active Pokémons you are tracking has changed!\n{{#if oldweather}}It went from {{oldweather}} {{oldweatheremoji}} to {{else}}It is now {{/if}}{{weather}} {
The plural here should be 'Pokémon'.   Line 199, too

2021-01-25 20:16 UTC, kbtbc approved these changes
Approved!  🥇  lol

2021-01-26 08:46 UTC, merged